### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by stuart23**

### CODE REVIEW

**Comment by stuart23** [comment]
@jwitz remember when I wanted to add a spell checker to the GH Action.........

**Review by kwcanuck — APPROVED** [review]

**Comment by kwcanuck** [comment]
@stuart23 this typo has already been addressed.

**Comment by jwitz** [comment]
@kwcanuck it looks like the typo is still on the main branch of the docs https://github.com/astronomer/docs/blob/main/astro/install-gcp.md . How did you end up correcting it? 

@stuart23 I still stand by that decision 🙈  but totally on me for not catching this spelling during my edit of Rob's PR

**Review by jwitz — APPROVED** [review]

**Comment by kwcanuck** [comment]
@jwitz the typo is corrected on main for me:

image

image
 
Did you do a pull this morning?

**Comment by kwcanuck** [comment]
@jwitz it appears that my edit didn't make it for some reason. Thank goodness @stuart23 caught it.

**Pull request merged**
