### PR TITLE
Add details around using non-Lets Encrypt certs in Standard Installation guides - Astronomer/issues/#1833

### PR DESCRIPTION
**Pull request by sunkickr**
Added note to standard install guide as recommended in issue #1833.

### CODE REVIEW

**Review by vparekh94 — CHANGES_REQUESTED** [review]
@sunkickr this is great - can you include an example of what that command would look like so it's clear for the users? e.g. something like

```bash
kubectl create secret tls astronomer-tls --key <path_to_key> --cert <path_to_cert> --namespace <my-namespace>
```

**Comment by paolaperaza** [comment]
Looks good, @sunkickr - thanks for doing this! My only thought here is that maybe we rephrase the note to be a little bit more actionable and a clear "If, then." So, I might say:

```
 **Note:** If you'd like to use another SSL Certificate authority, replace the paths to the Let's Encrypt cert and key .pem files with the paths to your certification's files in the command above.
```

Tbh I don't know what the "noun" here should be in terms of what to call an alternative to Lets Encrypt, so you guys replace that as needed. In other words, could be, "If you'd like to use another form of SSL Certification..." or "another SSL Certification...".

(and then include an example command like @vparekh94 said).

WDYT?

**Comment by sunkickr** [comment]
@paolaperaza I think the note could be a little more clear too. I like the way you phrased the note. I can make these changes and resubmit the PR.

**Comment by sunkickr** [comment]
Made all changes suggested also found a small typo in the document and updated that too.

**Review by paolaperaza — APPROVED** [review]
Awesome, thanks @sunkickr ! Looks good.

**Review by vparekh94 — APPROVED** [review]

**Pull request merged**
