### PR TITLE
Incorrect Key for Custom Software Alerts

### PR DESCRIPTION
**Pull request by fritz-astronomer**
Was trying to debug something with @ReadytoRocc and I think this is correct

### CODE REVIEW

**Review by jwitz — APPROVED** [review]
LGTM, I'm also going to make this change in earlier versions of the Software docs!

**Comment by jwitz** [comment]
After this is moved from draft state, I'll merge.

**Review by ReadytoRocc — APPROVED** [review]
LGTM

**Comment by fritz-astronomer** [comment]
Got final approval from @ReadytoRocc 👍 good to go

**Pull request merged**
