### PR TITLE
Add Doppler as a Supported Secrets Backend

### LINKED ISSUE #960: Use Doppler as a secrets backend
**Request type:**

- [ ] **New document:**: Add the `docs-content` label to this issue.
- [X] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

Explain how to use Doppler as an Airflow secrets backend on Astronomer. Starting guide is here: https://www.notion.so/astronomerio/Doppler-Astro-Integration-dd3c19f5949d4e899d752d1314c00b1c

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?** @manmeetkaur Should review

### PR DESCRIPTION
**Pull request by kwcanuck**
Resolves #960 

@manmeetkaur some questions for you:

- How should secrets be formatted on Doppler? Do they need to have a specific name format to be referenced in Airflow?

- Can DOPPLER_TOKEN be set as an environment variable on Astro? Do we need to set any additional variables on Astro?

- Which of the values in the Dockerfile are examples? What needs to be defined by the user?

There currently appears to be a lot of missing steps. In addition to answering the questions, could you indicate if any existing information in _[Configure an external secrets backend on Astro](https://docs.astronomer.io/astro/secrets-backend)_ can be reused? If it's easier, we can meet to discuss the documentation requirements and the current gaps.

@jwitz this PR isn't ready for your review yet. I'll let you know when it's ready. Thanks!

### CODE REVIEW

**Comment by manmeetkaur** [comment]
@kwcanuck please find the answers to the best of my ability based on my relatively new experience with Doppler:

- How should secrets be formatted on Doppler? Do they need to have a specific name format to be referenced in Airflow?
On Doppler we can create secrets just like any other environment variable. No need for a specific prefix etc. But general rules are [here](https://docs.doppler.com/docs/secrets#secret-names).  Doppler allows us to create separate environments in each project and we can easily refer those by passing relevant configs (See [here](https://docs.doppler.com/docs/secrets#referencing-across-projects)) . 

- Can DOPPLER_TOKEN be set as an environment variable on Astro? Do we need to set any additional variables on Astro?
We can set it up but we would still need it in the CI/CD environment, because the `DOPPLER_TOKEN` is required as an environment variable within the Dockerfile for running the `doppler` command. 

- Which of the values in the Dockerfile are examples? What needs to be defined by the user?
No Value in the Dockerfile is an example. All the rows that I mentioned will need to be set. In case of local development, `DOPPLER_TOKEN` will need to set in `.env` or your local environment. And in case of CI/CD it needs to be present in your GitHub Action Secrets

- There currently appears to be a lot of missing steps. In addition to answering the questions, could you indicate if any existing information in [Configure an external secrets backend on Astro](https://docs.astronomer.io/astro/secrets-backend) can be reused? If it's easier, we can meet to discuss the documentation requirements and the current gaps.

The thing is Doppler is not currently set as a Secrets Backend. It will be a separate Airflow PR to consider it as a Secrets Backend and we can raise this with Airflow Team. This way to integrate Doppler is our only option till we can register it as a Secrets Backend. 

So not sure, **_IF_** this goes in the docs, where will it reside, because functionally it is a Secrets Backend but it not registered/programmed to be one within Airflow. Hence we have to make changes to Dockerfile like this. Or may be hold-off on it until Airflow Team decides to include it ? I can talk to @kaxil about correct path on this. 

Let me know if you want to chat about it.

**Review by manmeetkaur — COMMENTED** [review]
@kwcanuck please find the answers to the best of my ability based on my relatively new experience with Doppler:

How should secrets be formatted on Doppler? Do they need to have a specific name format to be referenced in Airflow?
On Doppler we can create secrets just like any other environment variable. No need for a specific prefix etc. But general rules are [here](https://docs.doppler.com/docs/secrets#secret-names). Doppler allows us to create separate environments in each project and we can easily refer those by passing relevant configs (See [here](https://docs.doppler.com/docs/secrets#referencing-across-projects)) .

Can DOPPLER_TOKEN be set as an environment variable on Astro? Do we need to set any additional variables on Astro?
We can set it up but we would still need it in the CI/CD environment, because the DOPPLER_TOKEN is required as an environment variable within the Dockerfile for running the doppler command.

Which of the values in the Dockerfile are examples? What needs to be defined by the user?
No Value in the Dockerfile is an example. All the rows that I mentioned will need to be set. In case of local development, DOPPLER_TOKEN will need to set in .env or your local environment. And in case of CI/CD it needs to be present in your GitHub Action Secrets

There currently appears to be a lot of missing steps. In addition to answering the questions, could you indicate if any existing information in [Configure an external secrets backend on Astro](https://docs.astronomer.io/astro/secrets-backend) can be reused? If it's easier, we can meet to discuss the documentation requirements and the current gaps.

The thing is Doppler is not currently set as a Secrets Backend. It will be a separate Airflow PR to consider it as a Secrets Backend and we can raise this with Airflow Team. This way to integrate Doppler is our only option till we can register it as a Secrets Backend.

So not sure, IF this goes in the docs, where will it reside, because functionally it is a Secrets Backend but it not registered/programmed to be one within Airflow. Hence we have to make changes to Dockerfile like this. Or may be hold-off on it until Airflow Team decides to include it ? I can talk to @kaxil about correct path on this.

Let me know if you want to chat about it.

**Comment by kwcanuck** [comment]
@manmeetkaur please discuss this with @kaxil about this PR. We can't create documentation unless the functionality is officially supported. Let me know when it is officially supported, and we'll make sure it's documented.

**Comment by kwcanuck** [comment]
Closing this as there has been no response to my request for information. It appears that the request for documentation for this functionality was made too early.

**Pull request closed without merging**
