### PR TITLE
Formatting was wrong

### PR DESCRIPTION
**Pull request by stuart23**
Formatting

### CODE REVIEW

**Comment by paolaperaza** [comment]
Ah! This looked good on Astro and I didn't double check the Software version - we'll fix this

**Comment by stuart23** [comment]
Should be ok now
Fixed

**Review by paolaperaza — APPROVED** [review]

**Comment by paolaperaza** [comment]
Ok yes looks good on preview for me too - feel free 2 merge

**Comment by paolaperaza** [comment]
thank you @stuart23 !!!!!

**Pull request merged**
