### PR TITLE
Fix indentation issue (606)

### PR DESCRIPTION
**Pull request by kwcanuck**
Corrected the indentation issues identified in issue #606

### CODE REVIEW

**Review by paolaperaza — APPROVED** [review]
This LGTM @kwcanuck ! Thank you 🎉 

Before you merge: It looks like you pulled in changes from another branch, so the `install-azure-standard` changes are in here. Want to see if you can take those out since they're being reviewed in https://github.com/astronomer/docs/pull/667?

**Comment by kwcanuck** [comment]
@paolaperaza thanks for the quick review. Odd - I'm not sure why those other commits are appearing in this PR. Any suggestions on how best to remove them? Checkout and rebase?

**Review by rbankston — APPROVED** [review]
That looks great to me

**Comment by paolaperaza** [comment]
I think you're good with Jake's most recent commit! @kwcanuck You should do the honors and merge 😊

**Comment by kwcanuck** [comment]
A big thank you to @jwitz for saving the day. Much appreciated.

**Pull request merged**
