### PR TITLE
Removed `next` folder to reduce maintenance

### PR DESCRIPTION
**Pull request by jwitz**
@paolaperaza mentioned that maintaining the `next` folder is more work than it's worth, and I pretty much agree. There's a few reasons why it makes sense to remove it:

- Most platform changes aren't finalized until the week or two leading up to the release, so it's extremely rare to be updating this folder to prepare for a release (which is its main reason for existing). When we start preparing for a release, we can make a new version folder then and keep it in a PR instead of preemptively publishing. 
- With regards to updating version numbers in links and docs, we have to do the same maintenance regardless of whether we cut a new folder or maintain a `next` folder. It probably makes more sense to do all of this in one PR, rather than spread it across various PRs.
- This will make it easier for people to contribute to docs. The `next` concept was confusing, and it was more likely to get out of sync with multiple contributors than to stay as a reliable source of truth. 

For future releases, we'll create a new folder before the release and make any version-specific changes then. This shouldn't change the specific actions of our versioning workflow; it should only change when those actions are completed.

I know there's some logic related to the `next` folder on our website, so I'm adding @ryanahamilton and @samblackk for review to ensure that this won't affect how our docset versions are rendered. If it does, we should merge this only after we make whatever changes are necessary on the web end of things.

### CODE REVIEW

**Review by ryanahamilton — APPROVED** [review]
No strong opinions on this. If it improves your workflow, then I'm all for it.

I just opened astronomer/astro-site#290 to remove the website dependency on this directory.

I'd love to get @samblackk's blessing as well just in case there's another consideration I'm forgetting.

**Review by paolaperaza — APPROVED** [review]
Excellent, thank you @jwitz & @ryanahamilton! Will defer to you both to pull trigger when this PR is safe to merge from a Website standpoint.

**Review by samblackk — APPROVED** [review]
LGTM - just rebase and fix the conflicts before merge :)

**Comment by jwitz** [comment]
Thanks all! @ryanahamilton I think https://github.com/astronomer/astro-site/pull/290 is ready to merge as well now

**Comment by ryanahamilton** [comment]
Done!

>

**Pull request merged**
