### PR TITLE
add azure standard

### PR DESCRIPTION
**Pull request by chomipi88**

### CODE REVIEW

**Comment by lzdanski** [comment]
@chomipi88 - Is there a docs issue for any other docs changes that we'll need to make for standard cluster support on Azure? I think there might be other places we'll need to add mentions and other supporting information.

**Review by lzdanski — APPROVED** [review]
Confirmed in preview

**Comment by chomipi88** [comment]
@lzdanski i couldn't find any other references where we get into cloud specifics for Standard cluster support beyond this doc. This was a soft launch of Azure Standard clusters.
We're going to make a lot more noise with the launch of the Azure Native Service.

**Comment by lzdanski** [comment]
@chomipi88 - Awesome, thank you for being thorough!

**Pull request merged**
