### PR TITLE
Add logos to integrations, fix cardTitle img width

### LINKED ISSUE #2102: Add Logos to Integration Page
### Context

We have an integrations page in the `Learn` section of our docs that is commonly visited by OSS Airflow users looking to learn about how to use Airflow with popular 3rd party tooling: https://docs.astronomer.io/learn/category/integrations

image

In some ways, the homepage for this Integrations collection looks "broken" with all the folder icons. It's how Docusaurus does it, but it doesn't look great.

### Ask

Let's see if we can:

- [x] Add logos that appear next to each of these docs pages. For example, add the Snowflake logo to the Snowflake integration doc.
- [x] Define some consistent image size/type that's compatible with how we want it to look and that we can use in the future
- [x] See if we can fix the spacing/padding on the logos on the `Install Astro` homepage while we're at it

image

### PR DESCRIPTION
**Pull request by katiebrady-astro**
Fixes #2102 

This PR adds logos to the cards on the integrations page, as well as a small bug fix for images/logos used in `cardTitle`.

Screenshot 2023-04-04 at 1 36 08 PM
Screenshot 2023-04-04 at 1 36 16 PM

### CODE REVIEW

**Review by paolaperaza — APPROVED** [review]
This looks SO good @katiebrady-astro! LGTM in the deploy preview... I'll let you do a final check and merge ✅ 

Thank you!

**Review by TJaniF — APPROVED** [review]
❤️ this looks so amazing! 

The only question I have is with the Kafka one if we want to use the logo of OS Kafka or Confluent? I lean towards using the logo of the OS tool in general but the tutorial itself does use a Confluent cluster as an example, so in this case the confluent logo seems more fitting.

**Comment by katiebrady-astro** [comment]
@paolaperaza @TJaniF thanks, glad ya'll like it! 😄 

And no problem at all, super easy to switch the logos (thanks @jwitz for the `sidebar_custom_props`!). I went ahead and changed it to the Kafka one to see what it looks like. Here's where you can swap `kafka.png` with `confluent.png` in `airflow-kafka.md` to change it (or add an icon to any of the docs that support it).

Screenshot 2023-04-04 at 3 11 35 PM

Screenshot 2023-04-04 at 3 12 19 PM

**Comment by TJaniF** [comment]
@katiebrady-astro Awesome, thank you! And thanks for explaining how the logos work! Don't let my small question delay the merge of this, I think both logos look great and if there is a reason to use one or the other we can alway switch them later  :)

**Comment by paolaperaza** [comment]
Good to know how to change out those images, @katiebrady-astro! We can leave the Kafka one. Merging 🎉

**Pull request merged**
