### PR TITLE
Note on importing a namespace from airflow.cfg in Kubepodoperator Doc

### PR DESCRIPTION
**Pull request by paolaperaza**
Based on [a feature request ](https://github.com/astronomer/astronomer/issues/405) that turned into a docs issue, I just threw in a note in the KubePodOperator doc to guide users on importing their kube namespace from their deployment's airflow.cfg.

I haven't gotten a chance to try this myself and based these guidelines on a note from Greg, so figured I'd throw up a PR.

@andrewhharmon Not urgent, but any chance you could take a look at this?

### CODE REVIEW

**Comment by paolaperaza** [comment]
@andrewhharmon Know you had a related issue/question to this this week - did you get a chance to take a look at the blurb I wrote up for the KubePodOperator doc relating to importing a deployment's namespace from airflow.cfg?

**Comment by vparekh94** [comment]
@paolaperaza I think we can close this - I made a set of changes to this doc that encompassed this

**Comment by paolaperaza** [comment]
@vparekh94 Yikes, sorry for missing your comments in here earlier! Just took a look here again and I thought there was some content in my PR that's still worth including. I saw you threw in the example of importing the env variable, but I just pushed up a commit that cleans up the format of the section right below the example and adds some clarifying language around those parameters.

Ended up adding a few other things while I was in there (e.g. corrected the size of nodes that New Cloud supports, added clearer instructions on pulling images from a private registry).

Can keep this closed but feel free to take a look and gimme feedback if you have it V!

**Comment by vparekh94** [comment]
Thanks for your changes! Like most of them! Added a few low priority comments for whenever you get a chance.

**Comment by paolaperaza** [comment]
Nice thanks @vparekh94 ! Yay, made the changes you suggested ✅

**Pull request closed without merging**
