### PR TITLE
Update cosmos_dag.py

### PR DESCRIPTION
**Pull request by sreekarj18**
Getting key error due to upper case keys, but in dataframe they are in lower case, to resolve it they need to be changed to lower case

### CODE REVIEW

**Review by sreekarj18 — COMMENTED** [review]
Getting key error due to upper case keys, but in dataframe they are in lower case, to resolve it they need to be changed to lower case

**Comment by TJaniF** [comment]
Hello @sreekarj18 thank you for your PR! Good catch, this turned out to be database specific! 

I originally wrote the guide using a Postgres database, where the current upper-case `YEAR` is the correct key. But testing it with Snowflake just now, your version is the one that works. 
I think since the tutorial is written using Postgres, rather than changing the code it makes sense to add a comment at line 31 that says:

`# Note that if you are using another database than Postgres, you might need to adjust the pd.DataFrame column names in this code to be lowercase.`

@lzdanski @jwitz database specifics strike again. I think a code comment should be enough since the error is easy to interpret and fix for users with a database that creates lower case column names. But open to other opinions and to adding a note in the text as well :) 

@sreekarj18 if Laura and/or Jake agree with my comment idea feel free to change this PR to be just the insertion of that comment so you get the credit for finding this :)

**Comment by jwitz** [comment]
I like the idea of an in-code note! What about

`# Written for Postgres. If you are using database other than Postgres, you might need to adjust the pd.DataFrame column names in this code to be lowercase.`

**Comment by TJaniF** [comment]
Closing this PR in favour of #2301 :)

**Pull request closed without merging**
