### PR TITLE
Add Additional Options to astro config set Topic

### LINKED ISSUE #1149: Document the Astro CLI configuration options
**Request type:**

- [x] **New document:**: Add the `docs-content` label to this issue.
- [ ] **Addition to an existing document**: Add the `enhancement` label to this issue.

**What is the purpose of the document/enhancement? Select all that apply:**

- [ ] Document a new feature for an upcoming release. Add the appropriate release version label to this issue.
- [x] Information for an existing feature that isn't yet documented.
- [ ] Additional considerations/ reference material for an existing document.

**Problem/feature that requires documentation:**
The Astro CLI is configurable in `.astro/config.yaml`, e.g. to configure a custom webserver port for local dev. However, configuration is completely undocumented at the moment. We should document the available configs: https://github.com/astronomer/astro-cli/blob/3507c684e47e60c3f59534b359c95858c24d27d4/config/config.go#L51-L76

**Are you the right person to review a draft of the document for technical accuracy? If not, who is?**

### PR DESCRIPTION
**Pull request by kwcanuck**
Resolves #1149 

@BasPH as discussed, you'll need to validate the definitions for the new options. Please review and provide your feedback at your earliest convenience. If you're unable to provide ethe definitions, please recommend an alternate. Thanks!

### CODE REVIEW

**Review by jwitz — CHANGES_REQUESTED** [review]
@kwcanuck Thanks for getting the ball rolling on this! Per Bas' original GitHub issue, I do think we should turn this configuration into its own doc/ topic outside of the CLI command reference. Maybe in "Configure the CLI?"

But before we do that, @BasPH I think we need to discuss whether we should really be documenting all of these options. The Houston ones are for Software only, and even then I think a few of them should only be used by Astronomer team members for debugging customer installations. Before we take this further, we should review the configs here and make sure we're only publishing the ones that have relevance for customers and open source users.

**Comment by kwcanuck** [comment]
@jwitz I disagree that the additional options should be moved to another topic. Why make users jump to another topic? This information doesn't significantly lengthen the existing table, and some of the options might be removed after confirmation with @BasPH.

**Comment by BasPH** [comment]
@jwitz I'm okay with not documenting every single config if it's not useful to the customer, but do agree this list deserves its own doc e.g. "configuration reference" (just like command reference).

**Comment by jwitz** [comment]
Closing this PR out in favor of https://github.com/astronomer/docs/pull/1153!

**Pull request closed without merging**
