### PR TITLE
Use official Docker action for GitHub CI (Software Only)

### PR DESCRIPTION
**Pull request by stuart23**
I would prefer that we (CRE) didn't support the third party GitHub Action `elgohr/Publish-Docker-Github-Action@2.6`, especially the older version that is listed here.

Instead I think we should be recommending the official docker actions `docker/login-action@v1` & `docker/build-push-action@v2` which is the official [GitHub recommended method](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images).

### CODE REVIEW

**Comment by stuart23** [comment]
@jwitz who can I chat about GH actions with?

**Review by jwitz — APPROVED** [review]
Hey @stuart23 sorry for the late review on this! In general this LGTM, I think it's definitely best practice to use official tools whenever possible in our templates. Thanks for updating this in all doc versions as well. 

Have you verified that this template configuration works in a test repo on the latest version of Software? If not it's no worries, but I know that Astronomer deploys can sometimes have quirks even with standard deployment methods. Tagging @aspain in case he wants to take a look a what we'll be recommending on the Software side going forward, but feel free to merge.

**Comment by stuart23** [comment]
Hey @jwitz, no rush! I made sure it was all working on my [own repo](https://github.com/astronomer/stu-actions-test) before making this PR, but that was for Astro (which we have now changed the CI process for anyways). IDK if anyone has a repo with DAGs for an existing software deployment that we can test on?

**Comment by stuart23** [comment]
@jwitz with the old action, we specified `name: <dev-release-name>/airflow:ci-${{ github.sha }}` but with the docker action you specify the entire tag `registry.${BASE_DOMAIN}/<dev-release-name>/airflow:ci-${{ github.sha }}`

**Review by jwitz — APPROVED** [review]
Ah I see, didn't realize that was being used as the tag. In that case this looks good to me! Feel  free to squash and merge

**Pull request merged**
