### PR TITLE
Add step to replace Backport Provider with Provider for 2.0

### PR DESCRIPTION
**Pull request by kaxil**
We were missing this step and so a customer will see errors when they try to deploy AC >= 2.0 with a backport-provider

### CODE REVIEW

**Comment by kaxil** [comment]
Please feel free to amend the PR :)

**Comment by kaxil** [comment]
cc @wolfier in case you want to add something more here

**Comment by paolaperaza** [comment]
Sweet, thanks so much for this @kaxil ! Good call to add this, I'm sure it adds confusion. One general question for you: 

Do you think we should replace all instances of 2.0.0 in this doc with 2.1.0? Would you generally recommend that users on 1.10.x today go to 2.1 directly instead of 1.10.12 > 1.10.15 > 2.0.0 > 2.1.0, for example?

I added a note with that assumption, and I'm considering just replacing most references with `2.1` to keep it up to date or at the very least clarify in the note I added that you can replace 2.0.0 with the latest 2.0 minor release for the rest of the instructions below. Are there plans to do the same for the [OSS "Upgrade to 2.0" guide](https://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html), or does `Airflow 2.0+` cover it? In any case, lemme know what you think. This may be good for now.

cc: @jwitz Def would love your feedback here too.

**Comment by kaxil** [comment]
> Sweet, thanks so much for this @kaxil ! Good call to add this, it sounds like it was causing confusion. One general question for you:
> 
> Do you think we should replace all instances of 2.0.0 in this doc with 2.1.0? Would you generally recommend that users on 1.10.x today go to 2.1 directly instead of 1.10.12 > 1.10.15 > 2.0.0 > 2.1.0, for example?
> 
> I added a note with that assumption, and I'm considering just replacing most references with `2.1` to keep it up to date or at the very least clarify in the note I added that you can replace 2.0.0 with the latest 2.0 minor release for the rest of the instructions below to avoid maintenance on every minor release. Are there plans to do the same for the [OSS "Upgrade to 2.0" guide](https://airflow.apache.org/docs/apache-airflow/stable/upgrading-to-2.html), or does `Airflow 2.0+` cover it? In any case, lemme know what you think. This may be good for now.
> 
> cc: @jwitz Def would love your feedback here too.

Yes it should be safe to go to 2.1 -- @ernest-kr and the QA team has tested it. I will let them add the details

**Comment by paolaperaza** [comment]
Got it, thanks Kaxil. I just replaced most actionable references to 2.1, though I kept 2.0 to refer to the release more generally. @jwitz Want to give this a look?

**Review by jwitz — APPROVED** [review]
Looks great @kaxil and @paolaperaza ! Just made a few spelling fixes (not from this PR tho), gonna merge now.

**Pull request merged**
