### PR TITLE
Fixes #3015 - add scroll-margin-top to API sections

### LINKED ISSUE #3015: Bug when using link to specific API operation
### Issue Type

Issue with website functionality

### Links to Affected Docs

https://docs.astronomer.io/astro/api/platform-api-reference#tag/Deployment/operation/UpdateDeployment, as an example.

### The Issue or Context

When you use an anchor link in the API reference docs, there is a high chance that the page jumps to an unrelated API operation. It seems to get worse if you try using a link for an operation lower down on the page.

### Fix or Proposed Change

_No response_

### Additional Notes

_No response_

### Required Reviewers

_No response_

### PR DESCRIPTION
**Pull request by katiebrady-astro**
This PR fixes a bug where anchor links are scrolling past their corresponding section when using the link directly.

### CODE REVIEW

**Review by jwitz — CHANGES_REQUESTED** [review]
@katiebrady-astro Thanks for working on this fix! I just tried some random links, and it looks like the bug is still there. For example, clicking https://deploy-preview-3076--gallant-neumann-56599d.netlify.app/astro/api/iam-api-reference#tag/ApiToken/operation/DeleteApiToken takes me to https://deploy-preview-3076--gallant-neumann-56599d.netlify.app/astro/api/iam-api-reference#tag/Team/operation/UpdateTeamRoles, which is several sections higher up on the page.

**Comment by jwitz** [comment]
@katiebrady-astro As a side note, Docusaurus 3.0 is out, if anything in this blog looks like it could be useful for your development here please lmk and I'll upgrade! https://docusaurus.io/blog/releases/3.0

**Comment by katiebrady-astro** [comment]
Hey @jwitz so sorry for such a long delay but this should actually be fixed now! The "200 Success" Response Schema boxes were being auto "clicked" after page load causing the page to shift and scroll the window past where the anchor should take them. That should be resolved now! 👍

**Review by jwitz — APPROVED** [review]
Nice just confirmed it worked!! Thank you @katiebrady-astro

**Pull request merged**
