### PR TITLE
Add Astronomer logo to footer

### PR DESCRIPTION
**Pull request by jwitz**

### CODE REVIEW

**Review by paolaperaza — APPROVED** [review]
This works! We can spiff up the footer more in the next few months as part of our wider docs/website re-design.

**Comment by kwcanuck** [comment]
Wondering if it makes sense to align the logo with the existing copyright attribution:

image

Alternatively, the logo could be moved to the location where it appears on the Astronomer.io website:

image

Question: Should the current year be added to the copyright attribution?

image

**Review by kwcanuck — APPROVED** [review]

**Comment by jwitz** [comment]
I successfully aligned the elements as you described @kwcanuck and it looked good in isolation, but it looked a bit off in relation to the other list elements in the footer. 

Thinking this might look cleaner if it was center-aligned so I made those changes, what do you think?

**Comment by jwitz** [comment]
Screen Shot 2022-08-10 at 3 48 50 PM

**Pull request merged**
