### PR TITLE
Update Azure DevOps Doc to use valid values in tag

### PR DESCRIPTION
**Pull request by frankcash**
## Description

Previous version included predefined env vars that are available in GitLab <https://docs.gitlab.com/ee/ci/variables/predefined_variables.html> but not Azure DevOps <https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml>

### CODE REVIEW

**Review by jwitz — APPROVED** [review]
Thanks for this fix @frankcash ! Can you please also push this change to the other versions of the CICD doc? There should be a file for our Cloud docset, as well as additional files for other Enterprise versions. Once you do that, this is good to merge :)

**Comment by frankcash** [comment]
@jwitz please re-review

**Review by jwitz — APPROVED** [review]
Looks like you might have pulled in some recently merged branches into this PR, but I don't think that should be an issue (unless there's merge conflicts). Changes specific to this PR look good!

**Comment by frankcash** [comment]
Yeah, I have no idea how that weirdness got here

**Pull request merged**
