### PR TITLE
Add caution and warning colors, fixes #447

### LINKED ISSUE #447: Docusaurus Admonitions no longer have color
Some of our [Docusaurus Admonitions](https://docusaurus.io/docs/markdown-features/admonitions) broke after the site redesign: 
image (9)

These styles of note should all be colored in with the versions of colors that align with our theme style

### PR DESCRIPTION
**Pull request by allenbrady-astro**
Fixes #447

### CODE REVIEW

**Comment by paolaperaza** [comment]
@allenbrady-astro Thanks for this! This is what I'm seeing in the preview. The formatting and shade all look great to me. One question: Is there no way to make the `Caution` yellow? The red <> orange seem a little too close to distinguish insinctively.

image

image
image

**Comment by allenbrady-astro** [comment]
Hey @paolaperaza np! And we can totally roll back to the default yellow, just pushed a commit with this update 🙌 
image

**Review by paolaperaza — APPROVED** [review]
Oh amazing, that LGTM @allenbrady-astro ! Will let @jwitz take a look here in the morning and merge.

Thank you!!!!

**Comment by jwitz** [comment]
These LGTM! Thank you @allenbrady-astro ! 🚢

**Pull request merged**
