### PR TITLE
Added note on local auth

### PR DESCRIPTION
**Pull request by vparekh94**
From yesterday's snafu

### CODE REVIEW

**Comment by vparekh94** [comment]
For https://github.com/astronomer/issues/issues/1428

**Comment by paolaperaza** [comment]
@vparekh94 Looks like this is nested under the "Auth0" example - that right?

**Comment by vparekh94** [comment]
Not `auth0` just the `auth` section; https://github.com/astronomer/houston-api/blob/main/config/default.yaml#L134

**Comment by paolaperaza** [comment]
@vparekh94 I meant in the doc! Given the order of the H2 and H3 headers, it looks this note is nested in this order in `ee-integrating-auth-systems` -

`## Auth 0 Example` > `### Auth0 Configuration` > `### Astronomer Configuration` > `### Local Auth`> `#### Upgrade your Astronomer Deployment` .

The doc also has an AzureAD and Okta example at the `##` level - does this local auth note apply to all of them/is it worth shifting the hierarchy of where this goes?

**Comment by vparekh94** [comment]
Ahh, I see I see; you are right. Made appropriate changes!

**Comment by paolaperaza** [comment]
@vparekh94 I ported this over to our new docs repo and opened up a fresh PR here: https://github.com/astronomer/astro-docs/pull/9

Did some cleanup while I was in there - feel free to post comments/approve there. Closing this out!

**Pull request closed without merging**
