### PR TITLE
Add Astro Runtime Provider Packages versions to our Docs

### PR DESCRIPTION
**Pull request by odaneau-astro**
The goal of this PR is to provide the list of installed provider packages for each Astro Runtime version we support.

I automated the retrieval with a Python script:
```python
import json
import logging
import subprocess

import pandas as pd
import requests


def get_runtime_versions():
    # URL to fetch JSON data
    url = "https://updates.astronomer.io/astronomer-runtime"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
    else:
        print("Failed to retrieve data from the URL.")
    versions = list(data.get("runtimeVersions").keys())
    versions.sort(reverse=True)
    logging.info(versions)
    return versions


def cleanup(text: str):
    text = text.replace("\b", "")
    text = text.replace("\f", "")
    text = text.replace("\n", "")
    text = text.replace("\r", "")
    text = text.replace("\t", "")
    return text


def get_version_providers(runtime_version: str):
    # Use subprocess to run the docker command and capture its output
    cmd = f"docker run --rm -e AIRFLOW__LOGGING__LOGGING_LEVEL=CRITICAL quay.io/astronomer/astro-runtime:{runtime_version} airflow providers list --output json"
    # Parse the JSON output from the docker command
    output = subprocess.check_output(cmd, shell=True).decode("utf-8")
    output = cleanup(output)
    packages = json.loads(output)

    df = pd.DataFrame.from_records(packages, exclude=["description"])
    print(df.to_markdown(index=False))


if __name__ == "__main__":
    versions = get_runtime_versions()
    print(versions)
    for version in versions:
        print("")
        print("")
        print(f"## Runtime version {version}")
        try:
            get_version_providers(version)
        except Exception:
            print(f"! Could not get packages for {version}")
            continue

```

### CODE REVIEW

**Comment by odaneau-astro** [comment]
@lzdanski @jwitz: I would appreciate it if you could help me figure out where to put this in our docs since we don't really have an Astro Runtime section for it.

**Review by BasPH — COMMENTED** [review]
Nice! This would be a helpful reference. I'm missing the page in the menu. How about under Reference -> Astro Runtime? You can add that in docs/sidebarsAstro.js.

**Review by jwitz — COMMENTED** [review]
This is looking great @odaneau-astro ! We've needed this resource for a long time. One logistical question before we proceed:

I'd prefer if the docs team wasn't responsible for of maintaining and running the Python script. Is there someone on the Runtime team who could commit to running this script as part of a workflow and sharing the results either in #releases or in a docs PR for all Runtime releases?

**Comment by odaneau-astro** [comment]
That's good feedback. I shared the script above as a one-off thing not knowing what tools/processes already existed to update dynamic Docs content like this one. We can certainly loop in the Runtime team to formalize this. I'll ask in Slack and link the thread here.

**Comment by jwitz** [comment]
But we should hold off merging until Jed's finalized his solution for publishing provider versions on slack.

**Comment by odaneau-astro** [comment]
@jedcunningham bumping this thread

**Comment by jwitz** [comment]
Closing out in favor of https://github.com/astronomer/docs/pull/3754 :D

**Pull request closed without merging**
